In [4]:
import numpy as np
import pandas as pd
class GaussianNaiveBayes:
    def fit(self, X, y):
        self.classes = np.unique(y)
        self.mean = {}
        self.var = {}
        self.prior = {}
        for c in self.classes:
            X_c = X[y == c]
            self.mean[c] = np.mean(X_c, axis=0)
            self.var[c] = np.var(X_c, axis=0)
            self.prior[c] = len(X_c) / len(X)
    def gaussian_probability(self, class_idx, x):
        mean = self.mean[class_idx]
        var = self.var[class_idx]
        var = np.where(var == 0, 1e-9, var)
        numerator = np.exp(-((x - mean) ** 2) / (2 * var))
        denominator = np.sqrt(2 * np.pi * var)
        return numerator / denominator
    def predict(self, X):
        predictions = []
        for x in X:
            posteriors = []
            for c in self.classes:
                prior = np.log(self.prior[c])
                likelihood = np.sum(np.log(self.gaussian_probability(c, x)))
                posteriors.append(prior + likelihood)
            predictions.append(self.classes[np.argmax(posteriors)])
        return np.array(predictions)
df = pd.read_csv("/Users/keerti/Desktop/ML/dtree.csv")
for col in df.columns:
    df[col] = pd.factorize(df[col])[0]
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
print(df.head())
print(X[:5])
model = GaussianNaiveBayes()
model.fit(X, y)
pred = model.predict(X)
print("Predictions:", pred)
print("Actual:", y)
print("Accuracy:", np.mean(pred == y) * 100, "%")

   Age  Income  Student  Credit  Buy
0    0       0        0       0    0
1    0       0        0       1    0
2    1       0        0       0    1
3    2       1        0       0    1
4    2       2        1       0    1
[[0 0 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [2 1 0 0]
 [2 2 1 0]]
Predictions: [0 0 0 1 1 1 1 0 1 1 1 0 1 0]
Actual: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]
Accuracy: 78.57142857142857 %
