In [3]:
import numpy as np

arr = np.arange(1, 21)

print("Array:")
print(arr)

print("Shape:", arr.shape)

print("Maximum value:", arr.max())
print("Minimum value:", arr.min())

print("Mean:", arr.mean())
print("Standard Deviation:", arr.std())

matrix = arr.reshape(4, 5)

print("4 x 5 Matrix:")
print(matrix)

print("Second Row:")
print(matrix[1])

print("Third Column:")
print(matrix[:, 2])

Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Shape: (20,)
Maximum value: 20
Minimum value: 1
Mean: 10.5
Standard Deviation: 5.766281297335398
4 x 5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Second Row:
[ 6  7  8  9 10]
Third Column:
[ 3  8 13 18]


In [4]:
import numpy as np

A = np.array([10, 20, 30, 40, 50])
B = np.array([5, 10, 15, 20, 25])

print("Addition (A + B):")
print(A + B)

print("\nSubtraction (A - B):")
print(A - B)

print("\nMultiplication (A * B):")
print(A * B)

print("\nDivision (A / B):")
print(A / B)

print("\nSum of elements in A:")
print(np.sum(A))

Addition (A + B):
[15 30 45 60 75]

Subtraction (A - B):
[ 5 10 15 20 25]

Multiplication (A * B):
[  50  200  450  800 1250]

Division (A / B):
[2. 2. 2. 2. 2.]

Sum of elements in A:
150


In [7]:
import pandas as pd

data = {
    "Roll No": [101, 102, 103, 104, 105],
    "Name": ["Ravi", "Priya", "Kiran", "Anu", "Sita"],
    "Marks": [85, 92, 78, 88, 95]
}

df = pd.DataFrame(data)

print("DataFrame:")
print(df)

print("\nFirst Three Records:")
print(df.head(3))

print("\nAverage Marks:")
print(df["Marks"].mean())

print("\nStudent with Highest Marks:")
print(df.loc[df["Marks"].idxmax()])

print("\nStudent with Lowest Marks:")
print(df.loc[df["Marks"].idxmin()])

def grade(mark):
    if mark >= 90:
        return "A"
    elif mark >= 80:
        return "B"
    else:
        return "C"

df["Grade"] = df["Marks"].apply(grade)

print("\nDataFrame with Grade Column:")
print(df)

DataFrame:
   Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78
3      104    Anu     88
4      105   Sita     95

First Three Records:
   Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78

Average Marks:
87.6

Student with Highest Marks:
Roll No     105
Name       Sita
Marks        95
Name: 4, dtype: object

Student with Lowest Marks:
Roll No      103
Name       Kiran
Marks         78
Name: 2, dtype: object

DataFrame with Grade Column:
   Roll No   Name  Marks Grade
0      101   Ravi     85     B
1      102  Priya     92     A
2      103  Kiran     78     C
3      104    Anu     88     B
4      105   Sita     95     A


In [9]:
import pandas as pd

data = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "Price": [50000, 500, 1200, 10000],
    "Quantity": [10, 50, 30, 15]
}

df = pd.DataFrame(data)

df["Total Value"] = df["Price"] * df["Quantity"]

print("DataFrame with Total Value:")
print(df)

inventory_value = df["Total Value"].sum()

print("\nOverall Inventory Value:")
print(inventory_value)

DataFrame with Total Value:
    Product  Price  Quantity  Total Value
0    Laptop  50000        10       500000
1     Mouse    500        50        25000
2  Keyboard   1200        30        36000
3   Monitor  10000        15       150000

Overall Inventory Value:
711000


In [12]:
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()

df = pd.DataFrame(iris.data, columns=iris.feature_names)

df["Species"] = iris.target

df["Species"] = df["Species"].map({
    0: "setosa",
    1: "versicolor",
    2: "virginica"
})

print("Iris DataFrame:")
print(df)

print("\nFirst Five Records:")
print(df.head())

print("\nNumber of Rows and Columns:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nSummary Statistics:")
print(df.describe())

print("\nSamples in Each Class:")
print(df["Species"].value_counts())

Iris DataFrame:
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       Spec